steps:
  - name: gcr.io/k8s-skaffold/pack
    env:
      - GOOGLE_ENTRYPOINT=$_ENTRYPOINT
    args:
      - build
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - '--builder=gcr.io/buildpacks/builder:v1'
      - '--network=cloudbuild'
      - '--path=.'
      - '--env=GOOGLE_ENTRYPOINT'
    id: Buildpack
    entrypoint: pack
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - >-
        --image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--update-secrets=OPENAI_API_KEY=openai-api-key:latest,TUSFACTURAS_API_KEY=tusfacturas-api-key:latest,TUSFACTURAS_API_TOKEN=tusfacturas-api-token:latest,TUSFACTURAS_USER_TOKEN=tusfacturas-user-token:latest,WHATSAPP_ACCESS_TOKEN=whatsapp-access-token:latest,POSTGRES_PASSWORD=postgres-password:latest,GEMINI_API_KEY=gemini-api-key:latest'
      - '--set-env-vars=POSTGRES_HOST=ep-delicate-moon-a4dnrer6-pooler.us-east-1.aws.neon.tech,POSTGRES_PORT=5432,POSTGRES_DB=neondb,POSTGRES_USER=neondb_owner,POSTGRES_CONNECT_OPTIONS=endpoint=ep-delicate-moon-a4dnrer6'
      - '--network=default'
      - '--subnet=default'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - >-
    $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _PLATFORM: managed
  _TRIGGER_ID: 4c33491b-9e39-4098-a0c9-b831c0369b30
  _SERVICE_NAME: accounting-ai-assistant-chat
  _AR_REPOSITORY: cloud-run-source-deploy
  _ENTRYPOINT: uvicorn app.main:app --host=0.0.0.0 --port=${PORT:-8080}
  _DEPLOY_REGION: us-central1
  _AR_PROJECT_ID: voicein-456423
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - accounting-ai-assistant-chat
